AttributeError: module 'gym_duckietown.tasks.lf_challenge.solutions.solution' has no attribute 'LfChallengeTaskSolution'
False: Non-zero return code, probably a syntax error occurred\ntime=1606299875.2595856 gym-duckietown 2019.0.0

time=1606299875.5003583 Registering gym environment id: Duckietown-4way-v0
time=1606299875.5005336 Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
time=1606299875.5006382 Registering gym environment id: Duckietown-loop_empty-v0
time=1606299875.5007591 Registering gym environment id: Duckietown-loop_obstacles-v0
time=1606299875.5008814 Registering gym environment id: Duckietown-loop_pedestrians-v0
time=1606299875.501008 Registering gym environment id: Duckietown-small_loop-v0
time=1606299875.501098 Registering gym environment id: Duckietown-small_loop_cw-v0
time=1606299875.501174 Registering gym environment id: Duckietown-straight_road-v0
time=1606299875.5012503 Registering gym environment id: Duckietown-straight_road_10_tiles_no_start_tile-v0
time=1606299875.5014486 Registering gym environment id: Duckietown-straight_road_no_start_tile-v0
time=1606299875.5015297 Registering gym environment id: Duckietown-straight_road_trafficlight-v0
time=1606299875.5016098 Registering gym environment id: Duckietown-straight_road_with_side_floor-v0
time=1606299875.5016875 Registering gym environment id: Duckietown-udem1-v0
time=1606299875.5017645 Registering gym environment id: Duckietown-zigzag_dists-v0
[ WARN:0] global /tmp/pip-req-build-qacpj5ci/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/checker.py", line 6, in <module>
    checkers=[RewardChecker()]
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/solution_evaluator.py", line 33, in __init__
    self.solution_class = getattr(solution_file_as_module, solution_class_name)
AttributeError: module 'gym_duckietown.tasks.lf_challenge.solutions.solution' has no attribute 'LfChallengeTaskSolution'
